# Generated by Django 4.0.3 on 2022-03-22 21:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastros',
            fields=[
                ('users', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('nascimento', models.DateField()),
            ],
        ),
    ]
